const typed = new Typed('.typed', {
    strings: ['<i class="welcome">mantenimiento</i>',
        '<i class="welcome">reparación</i>',
        '<i class="welcome">venta</i>',
        '<i class="welcome">actualización</i>',
        '<i class="welcome">armado</i>',
    ],
    //stringsElement: '#cadenas-texto',
    typeSpeed: 80,
    StartDelay: 300,
    backSpeed: 80,
    smartBackspace: true,
    shuffle: false,
    backDelay: 1500,
    loop: true,
    loopCount: false,
    showCursor: true,
    cursorChar: '|',
    contentType: 'html',
});